REFRESH_RATE = 0.001

SPEED_RUN = 4
SPEED_WALK = 2
SPEED_CROUCH = 1

MOTION_RUN = 1
MOTION_CROUCH = 2
MOTION_JUMP = 3
MOTION_WALK = 4
MOTION_DEATH = 5

MOVE_IDLE = 0
MOVE_RUN = 1
MOVE_BACK = 2
MOVE_LEFT = 3
MOVE_RIGHT = 4
MOVE_RUN_LEFT = 5
MOVE_RUN_RIGHT = 6
MOVE_BACK_LEFT = 7
MOVE_BACK_RIGHT = 8

ATTACK_IDLE = 0
ATTACK_SINGLE = 1
ATTACK_BURST = 2
ATTACK_RELOAD = 3
ATTACK_THROW = 4

ENEMY_STATE_IDLE = 0
ENEMY_STATE_MOVE = 1
ENEMY_STATE_ATTACK = 2
ENEMY_STATE_DEATH = 3
ENEMY_STATE_DIZZY = 4
